// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sherlook22/cortex/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockMemoryRepository is an autogenerated mock type for the MemoryRepository type
type MockMemoryRepository struct {
	mock.Mock
}

type MockMemoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemoryRepository) EXPECT() *MockMemoryRepository_Expecter {
	return &MockMemoryRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockMemoryRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMemoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMemoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMemoryRepository_Delete_Call {
	return &MockMemoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMemoryRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockMemoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMemoryRepository_Delete_Call) Return(_a0 error) *MockMemoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemoryRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockMemoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTopicKey provides a mock function with given fields: ctx, topicKey, project, scope
func (_m *MockMemoryRepository) FindByTopicKey(ctx context.Context, topicKey string, project string, scope domain.Scope) (*domain.Memory, error) {
	ret := _m.Called(ctx, topicKey, project, scope)

	if len(ret) == 0 {
		panic("no return value specified for FindByTopicKey")
	}

	var r0 *domain.Memory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.Scope) (*domain.Memory, error)); ok {
		return rf(ctx, topicKey, project, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.Scope) *domain.Memory); ok {
		r0 = rf(ctx, topicKey, project, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Memory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.Scope) error); ok {
		r1 = rf(ctx, topicKey, project, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_FindByTopicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTopicKey'
type MockMemoryRepository_FindByTopicKey_Call struct {
	*mock.Call
}

// FindByTopicKey is a helper method to define mock.On call
//   - ctx context.Context
//   - topicKey string
//   - project string
//   - scope domain.Scope
func (_e *MockMemoryRepository_Expecter) FindByTopicKey(ctx interface{}, topicKey interface{}, project interface{}, scope interface{}) *MockMemoryRepository_FindByTopicKey_Call {
	return &MockMemoryRepository_FindByTopicKey_Call{Call: _e.mock.On("FindByTopicKey", ctx, topicKey, project, scope)}
}

func (_c *MockMemoryRepository_FindByTopicKey_Call) Run(run func(ctx context.Context, topicKey string, project string, scope domain.Scope)) *MockMemoryRepository_FindByTopicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(domain.Scope))
	})
	return _c
}

func (_c *MockMemoryRepository_FindByTopicKey_Call) Return(_a0 *domain.Memory, _a1 error) *MockMemoryRepository_FindByTopicKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_FindByTopicKey_Call) RunAndReturn(run func(context.Context, string, string, domain.Scope) (*domain.Memory, error)) *MockMemoryRepository_FindByTopicKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, project
func (_m *MockMemoryRepository) GetAll(ctx context.Context, project string) ([]domain.Memory, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Memory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Memory, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Memory); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Memory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMemoryRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
func (_e *MockMemoryRepository_Expecter) GetAll(ctx interface{}, project interface{}) *MockMemoryRepository_GetAll_Call {
	return &MockMemoryRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, project)}
}

func (_c *MockMemoryRepository_GetAll_Call) Run(run func(ctx context.Context, project string)) *MockMemoryRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemoryRepository_GetAll_Call) Return(_a0 []domain.Memory, _a1 error) *MockMemoryRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_GetAll_Call) RunAndReturn(run func(context.Context, string) ([]domain.Memory, error)) *MockMemoryRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMemoryRepository) GetByID(ctx context.Context, id int64) (*domain.Memory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Memory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Memory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Memory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Memory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMemoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockMemoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMemoryRepository_GetByID_Call {
	return &MockMemoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMemoryRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockMemoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockMemoryRepository_GetByID_Call) Return(_a0 *domain.Memory, _a1 error) *MockMemoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Memory, error)) *MockMemoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecent provides a mock function with given fields: ctx, project, sessionID, limit
func (_m *MockMemoryRepository) GetRecent(ctx context.Context, project string, sessionID string, limit int) ([]domain.Memory, error) {
	ret := _m.Called(ctx, project, sessionID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []domain.Memory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) ([]domain.Memory, error)); ok {
		return rf(ctx, project, sessionID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) []domain.Memory); ok {
		r0 = rf(ctx, project, sessionID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Memory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, project, sessionID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_GetRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecent'
type MockMemoryRepository_GetRecent_Call struct {
	*mock.Call
}

// GetRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - sessionID string
//   - limit int
func (_e *MockMemoryRepository_Expecter) GetRecent(ctx interface{}, project interface{}, sessionID interface{}, limit interface{}) *MockMemoryRepository_GetRecent_Call {
	return &MockMemoryRepository_GetRecent_Call{Call: _e.mock.On("GetRecent", ctx, project, sessionID, limit)}
}

func (_c *MockMemoryRepository_GetRecent_Call) Run(run func(ctx context.Context, project string, sessionID string, limit int)) *MockMemoryRepository_GetRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockMemoryRepository_GetRecent_Call) Return(_a0 []domain.Memory, _a1 error) *MockMemoryRepository_GetRecent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_GetRecent_Call) RunAndReturn(run func(context.Context, string, string, int) ([]domain.Memory, error)) *MockMemoryRepository_GetRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, project
func (_m *MockMemoryRepository) GetStats(ctx context.Context, project string) (*domain.Stats, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Stats, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Stats); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockMemoryRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
func (_e *MockMemoryRepository_Expecter) GetStats(ctx interface{}, project interface{}) *MockMemoryRepository_GetStats_Call {
	return &MockMemoryRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, project)}
}

func (_c *MockMemoryRepository_GetStats_Call) Run(run func(ctx context.Context, project string)) *MockMemoryRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMemoryRepository_GetStats_Call) Return(_a0 *domain.Stats, _a1 error) *MockMemoryRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_GetStats_Call) RunAndReturn(run func(context.Context, string) (*domain.Stats, error)) *MockMemoryRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, memory
func (_m *MockMemoryRepository) Save(ctx context.Context, memory *domain.Memory) (int64, error) {
	ret := _m.Called(ctx, memory)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Memory) (int64, error)); ok {
		return rf(ctx, memory)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Memory) int64); ok {
		r0 = rf(ctx, memory)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Memory) error); ok {
		r1 = rf(ctx, memory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMemoryRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - memory *domain.Memory
func (_e *MockMemoryRepository_Expecter) Save(ctx interface{}, memory interface{}) *MockMemoryRepository_Save_Call {
	return &MockMemoryRepository_Save_Call{Call: _e.mock.On("Save", ctx, memory)}
}

func (_c *MockMemoryRepository_Save_Call) Run(run func(ctx context.Context, memory *domain.Memory)) *MockMemoryRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Memory))
	})
	return _c
}

func (_c *MockMemoryRepository_Save_Call) Return(_a0 int64, _a1 error) *MockMemoryRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.Memory) (int64, error)) *MockMemoryRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImport provides a mock function with given fields: ctx, memory
func (_m *MockMemoryRepository) SaveImport(ctx context.Context, memory *domain.Memory) (int64, error) {
	ret := _m.Called(ctx, memory)

	if len(ret) == 0 {
		panic("no return value specified for SaveImport")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Memory) (int64, error)); ok {
		return rf(ctx, memory)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Memory) int64); ok {
		r0 = rf(ctx, memory)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Memory) error); ok {
		r1 = rf(ctx, memory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_SaveImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImport'
type MockMemoryRepository_SaveImport_Call struct {
	*mock.Call
}

// SaveImport is a helper method to define mock.On call
//   - ctx context.Context
//   - memory *domain.Memory
func (_e *MockMemoryRepository_Expecter) SaveImport(ctx interface{}, memory interface{}) *MockMemoryRepository_SaveImport_Call {
	return &MockMemoryRepository_SaveImport_Call{Call: _e.mock.On("SaveImport", ctx, memory)}
}

func (_c *MockMemoryRepository_SaveImport_Call) Run(run func(ctx context.Context, memory *domain.Memory)) *MockMemoryRepository_SaveImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Memory))
	})
	return _c
}

func (_c *MockMemoryRepository_SaveImport_Call) Return(_a0 int64, _a1 error) *MockMemoryRepository_SaveImport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_SaveImport_Call) RunAndReturn(run func(context.Context, *domain.Memory) (int64, error)) *MockMemoryRepository_SaveImport_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query
func (_m *MockMemoryRepository) Search(ctx context.Context, query domain.SearchQuery) ([]domain.SearchResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchQuery) ([]domain.SearchResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchQuery) []domain.SearchResult); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SearchQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMemoryRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMemoryRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.SearchQuery
func (_e *MockMemoryRepository_Expecter) Search(ctx interface{}, query interface{}) *MockMemoryRepository_Search_Call {
	return &MockMemoryRepository_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockMemoryRepository_Search_Call) Run(run func(ctx context.Context, query domain.SearchQuery)) *MockMemoryRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SearchQuery))
	})
	return _c
}

func (_c *MockMemoryRepository_Search_Call) Return(_a0 []domain.SearchResult, _a1 error) *MockMemoryRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryRepository_Search_Call) RunAndReturn(run func(context.Context, domain.SearchQuery) ([]domain.SearchResult, error)) *MockMemoryRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, params
func (_m *MockMemoryRepository) Update(ctx context.Context, id int64, params domain.UpdateParams) error {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateParams) error); ok {
		r0 = rf(ctx, id, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMemoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - params domain.UpdateParams
func (_e *MockMemoryRepository_Expecter) Update(ctx interface{}, id interface{}, params interface{}) *MockMemoryRepository_Update_Call {
	return &MockMemoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, params)}
}

func (_c *MockMemoryRepository_Update_Call) Run(run func(ctx context.Context, id int64, params domain.UpdateParams)) *MockMemoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.UpdateParams))
	})
	return _c
}

func (_c *MockMemoryRepository_Update_Call) Return(_a0 error) *MockMemoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemoryRepository_Update_Call) RunAndReturn(run func(context.Context, int64, domain.UpdateParams) error) *MockMemoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemoryRepository creates a new instance of MockMemoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemoryRepository {
	mock := &MockMemoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
