// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sherlook22/cortex/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *MockSessionRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Session))
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(_a0 error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(context.Context, *domain.Session) error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function with given fields: ctx, id, summary
func (_m *MockSessionRepository) EndSession(ctx context.Context, id string, summary string) error {
	ret := _m.Called(ctx, id, summary)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type MockSessionRepository_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - summary string
func (_e *MockSessionRepository_Expecter) EndSession(ctx interface{}, id interface{}, summary interface{}) *MockSessionRepository_EndSession_Call {
	return &MockSessionRepository_EndSession_Call{Call: _e.mock.On("EndSession", ctx, id, summary)}
}

func (_c *MockSessionRepository_EndSession_Call) Run(run func(ctx context.Context, id string, summary string)) *MockSessionRepository_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSessionRepository_EndSession_Call) Return(_a0 error) *MockSessionRepository_EndSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_EndSession_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSessionRepository_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *MockSessionRepository) GetSession(ctx context.Context, id string) (*domain.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepository_Expecter) GetSession(ctx interface{}, id interface{}) *MockSessionRepository_GetSession_Call {
	return &MockSessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, id)}
}

func (_c *MockSessionRepository_GetSession_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) Return(_a0 *domain.Session, _a1 error) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_GetSession_Call) RunAndReturn(run func(context.Context, string) (*domain.Session, error)) *MockSessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with given fields: ctx, project, limit
func (_m *MockSessionRepository) ListSessions(ctx context.Context, project string, limit int) ([]domain.Session, error) {
	ret := _m.Called(ctx, project, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.Session, error)); ok {
		return rf(ctx, project, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.Session); ok {
		r0 = rf(ctx, project, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, project, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockSessionRepository_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - limit int
func (_e *MockSessionRepository_Expecter) ListSessions(ctx interface{}, project interface{}, limit interface{}) *MockSessionRepository_ListSessions_Call {
	return &MockSessionRepository_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, project, limit)}
}

func (_c *MockSessionRepository_ListSessions_Call) Run(run func(ctx context.Context, project string, limit int)) *MockSessionRepository_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockSessionRepository_ListSessions_Call) Return(_a0 []domain.Session, _a1 error) *MockSessionRepository_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_ListSessions_Call) RunAndReturn(run func(context.Context, string, int) ([]domain.Session, error)) *MockSessionRepository_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
