with-expecter: true
dir: "internal/tests/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  github.com/sherlook22/cortex/internal/domain:
    interfaces:
      MemoryRepository:
